### ISSUE TITLE
modify the coordinateMetadata for old stacks

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub/iohub#106]
@ziw-liu @talonchandler @mattersoflight 
From our discussion during our lab meeting, there seems to be a need for us to be able to implement an API call that allows us to modify the coordinate metadata for the datastore.

Currently, to modify the coordinateMetadata I think one has to do the following for each `Position` (please correct me if I'm wrong):
```python
## Test writing to the metadata for existing arrays
dataset = open_ome_zarr(store_path, mode='r+')
print(dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'])
dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'][0]['translation']  = [0, 0, 0, 500, 500]
print(dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'])
dataset.close()
```

This is a lower-priority enhancement, but we will benefit from this to display the multiple positions without having to copy or duplicate data.

**Comment by ziw-liu** [comment]
Another way to do the same thing as your snippet is:

```py
transform = iohub.ngff.TransformationMeta(type="translation", translation=[0, 0, 0, 500, 500])

position = dataset["0/0/0"]

position.metadata.multiscales[0].datasets[0].coordinate_transformations[0] = transform
```

This is way you get the autocompletion, but it's still quite verbose so a convenience method might make sense. For example in the form of: 

```py
class Position(...):
    ...
    def set_transorm(self, img: int | Literal["all"], transform: TransformationMeta):
    ...
```
