### ISSUE TITLE
NDTiffReader cannot be pickled

### ISSUE THREAD

**Issue by ieivanov** [czbiohub/iohub#121]
```python
reader = read_micromanager(\path\to\ndtiff\dataset)
pickle.dumps(reader)
```

throws `TypeError: cannot pickle '_thread.RLock' object` error. Being able to pickle the reader is important for multiprocessing. I'm using python 3.9.16

**Comment by JoOkuma** [comment]
Hi Ivan, is it an option to pickle the path rather then the reader? Than inside each process you create its own reader instance.Sent from my iPhoneOn Apr 25, 2023, at 17:03, Ivan Ivanov ***@***.***> wrote:﻿
reader = read_micromanager(\path\to\ndtiff\dataset)
pickle.dumps(reader)
throws TypeError: cannot pickle '_thread.RLock' object error. Being able to pickle the reader is important for multiprocessing. I'm using python 3.9.16

**Comment by ieivanov** [comment]
That's a possible workaround, but it's not very efficient as initializing the reader takes a bit of time for larger datasets.

After another minute of debugging, I found that the problem stems from the `ndtiff` library itself. Closing this issue here
