### ISSUE TITLE
Use built-in generics to annotate sequence types

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#126]
As we drop 3.8 support, built-in generics (`list[...]`, `tuple[...]`) can be used to annotate types instead of `List` and `Tuple` from `typing`.

Old code should be cleaned up for consistency.

**Comment by mattersoflight** [comment]
👍🏼 I am linking here the [PEP](https://peps.python.org/pep-0585/) on type hinting support in python 3.9 to provide more context.
