### ISSUE TITLE
License of the documentation

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#130]
Now the docs web page says (per sphinx theme default):

> © Copyright 2023. Chan Zuckerberg Biohub. All rights reserved.

Which is confusing because we are probably want to allow free use of the compiled documentation.

Maybe use something like [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)?

**Comment by ziw-liu** [comment]
@keithchev pointed out that this is OK since it's using the same language in the BSD-3 clause license.

@AhmetCanSolak Do you have any suggestion?

**Comment by AhmetCanSolak** [comment]
I think it should stay as is. We are not using copyright in any non-defensive manner. IP team approved that Copyright line previously.
