### ISSUE TITLE
`create_position` fails after closing and reopening a dataset 

### ISSUE THREAD

**Issue by talonchandler** [czbiohub/iohub#135]
This snippet demonstrates the issue:
```
from iohub import open_ome_zarr
dataset = open_ome_zarr('./test.zarr', layout="hcs", mode="a", channel_names=["1", "2"])
dataset.create_position("0", "0", "0") # WORKS
dataset.create_position("0", "1", "0") # WORKS
dataset.close()

# Reopen
dataset = open_ome_zarr('./test.zarr', layout="hcs", mode="a", channel_names=["1", "2"])
dataset.create_position("0", "2", "0") # FAILS
# ContainsGroupError: path '0' contains a group
```

This functionality is essential for slurm processing of zarr datasets, where a single node works on a single position and appends to an output zarr store when it finishes. Related: https://github.com/czbiohub/mantis/pull/33

**Comment by talonchandler** [comment]
I suspect this line to the source of the problem: 

https://github.com/czbiohub/iohub/blob/8418014ad83b0189e945e12cb0e2538d153c87e8/iohub/ngff.py#LL1437C8-L1437C8

`well_path` takes the form `0/0`, while `self.zgroup` takes the form `0`.

**Comment by ziw-liu** [comment]
It is indeed a bug. Caused by init logic of some internal state of the `Plate` object. Will fix shortly.
