### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#144]
### [`transferred_issues`](https://github.com/czbiohub/iohub/tree/transferred_issues)
On this branch we have 3 transferred issues:
- 272 and 277 is completed
- 276 is partially out of scope and partially a duplicate of #99 

### [`ngff-api`](https://github.com/czbiohub/iohub/tree/ngff-api)
This was a temporary dev branch and has been further developed in #45 

@mattersoflight Can we delete these?

**Comment by mattersoflight** [comment]
@ziw-liu yes makes sense to delete the above branches. Thanks.

**Comment by ziw-liu** [comment]
Done.
