### ISSUE TITLE
support multi-pos datasets that are not complete multi-well plate acquisitions

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub/iohub#22]
There is an apparent gap in data formats specified by OME-NGFF and supported by `napari-ome-zarr` plugin: they specify/support single FOV ND arrays or multi-FOV ND arrays acquired in a multi-well plate, but not simple multi-pos acquisitions. 

We can represent this data as as a multi-well dataset to leverage the `napari-ome-zarr` plugin for visualization.

This topic requires a discussion among @ziw-liu , @Soorya19Pradeep , @jrbyrum13 , @Christianfoley , @ieivanov, @talonchandler  who either acquire or analyze multi-pos datasets. 

I see two options:
1. Have a single column, with row names = position names in micro-manager acquisition . 
2. Map the data to a square grid to make it easy to visualize with napari plugin, e.g., if we have 100 FOVs, sort them into 10 rows and 10 columns. 

Votes & Ideas?

**Comment by ziw-liu** [comment]
I think the current API is expressive enough to store arbitrary HCS-conformant layouts.

If there's a specific problem/question about usage, please open a separate issue.
