### ISSUE TITLE
Open source iohub

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#47]
At this stage I think iohub repository are mostly meeting our organization's requirements, as well as the general expectations for an early-stage open source project. And I propose that we make this repository public once #46 is merged.

Tagging @mattersoflight @AhmetCanSolak @JoOkuma to see if you have any concerns.

**Comment by AhmetCanSolak** [comment]
We were ready to continue developing in public, but I can't say we're mostly meeting our organization's requirements yet. I will continue to talk with different teams to start them as early adapters.

Small note to @mattersoflight : Please give everyone more time to put their inputs on repository wide decisions. Maybe we were thinking it is time to go open, but not necessarily everyone involved agreed. As a good practice in async communication, let's give everyone at least a 24h before taking any major actions.  We want to be as inclusive as possible, especially now that we are accepting external contributors.

**Comment by mattersoflight** [comment]
@AhmetCanSolak certainly. What are the remaining requirements?

**Comment by AhmetCanSolak** [comment]
I will be making separate issues, like #57
