### ISSUE TITLE
`README` example does not run; opens in read-only by default

### ISSUE THREAD

**Issue by talonchandler** [czbiohub/iohub#52]
In the `iohub`'s README we have:

```
with open_ome_zarr("20200812-CardiomyocyteDifferentiation14-Cycle1.zarr") as dataset:
    ...
    new_fov = dataset.create_position("A", "1", "0")  # creates a new fov
    ...
```
which fails because by default `open_ome_zarr` opens in read-only mode. 

Adding `mode='r+'` works, but it modified/added to the dataset I downloaded from the web, then failed on subsequent runs (since the position already existed when I ran it the first time). 

Maybe a more user-friendly README example should read the example dataset, write to a new file, then read+append to that new file?

**Comment by talonchandler** [comment]
PS I love `.print_tree` and the `create_position` API. Both are big steps forward compared to our old readers.

**Comment by ziw-liu** [comment]
Ah, I mistakenly deleted the file mode option `mode="a"` at some point. Will fix shortly.

**Comment by ziw-liu** [comment]
> Maybe a more user-friendly README example should read the example dataset, write to a new file, then read+append to that new file?

Great idea!
