### ISSUE TITLE
Dev pre-release on PyPI

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#55]
A pre-release on PyPI can ease testing for downstream projects such as recOrder and microDL, and help us navigate PyPI issues before the 'stable' release. Once we have most of the 0.1.0 features ready we can tag a `v0.1.0dev0` and use this issue to track the process.

**Comment by AhmetCanSolak** [comment]
I would suggest we go with `v.0.0.1` when most features are ready @ziw-liu . We can have a shorther release cycle at the beginning but it is more important to not rush things at the beginning of our longer journey.

**Comment by ziw-liu** [comment]
> I would suggest we go with `v.0.0.1` when most features are ready @ziw-liu .

From my interpretation of semantic versioning the third digit is used for patches, e.g. when we have a first release of `v0.1.0` we can have a maintenance branch called `patches/0.1.x` and the patched version will be `v0.1.1` etc. Whenever a API is changed I think it is advised to increment the second digit, but I'm honestly not sure if `v0.0.0` is a valid version number.

**Comment by AhmetCanSolak** [comment]
My experience is that people get (easily) upset as you break APIs they build on, even if you are only on minor versions.  So my suggestion is mostly about being less promising to API users, I don't think anyone would get upset by not following semantic versioning conventions.  I suspect we will develop and break many places in the near timeline.

**Comment by talonchandler** [comment]
I would like to start the process of making `recOrder` and `waveorder` depend on `iohub`. 

I'm planning to:
1. Assist with any decisions that need to be made to merge #92. @ziw-liu can you comment here or on #92 with your suggestion for the best path forward. I think our collective decision on Monday was to rename `imread` then merge?
2. Tag the commit with a name like `v0.1.0dev0` (I'm open to suggestions) without releasing to PyPI.
3. Remove `WaveorderReader` from `waveorder` and depend on the tagged version of `iohub` via github. After testing, release `waveorder==1.0.0`.
4. Remove `WaveorderReader` from `recOrder` and depend on the tagged version of `iohub` via github. 

I think merging #92 is the current blocker, so I would appreciate progress and discussion on that point.

**Comment by mattersoflight** [comment]
@ziw-liu as we discussed offline, instead of a dev pre-release on pyPI, let's create a tag. Both @talonchandler and @ieivanov are eager to start depending on `iohub` in recOrder, waveOrder, mantis. And, I hear from you that you want to start depending on `iohub` in microDL. 

It makes sense to create a tag and update the installation instructions in README and docs once have the features needed by these four repos. Do we need to merge open PRs (#91 and #97) before the dev release?

**Comment by ziw-liu** [comment]
@mattersoflight thanks for summarizing the discussion. I think a `dev` tag is very low stake and I am happy with or without merging #97 (just merged #91).

As for the documentation update I don't know the upcoming tag will be better for user installation than the HEAD of `main` since they are both not intended to be stable, and bleeding edge may have more bug fixes.

**Comment by talonchandler** [comment]
#97 isn't necessary for `recOrder` in the near term. It will be convenient to have eventually for the corner case of analyzing 2D+3D MM acquisitions, but I now have workarounds for data acquired on the spindle project. 

I don't anticipate 2D+3D acquisitions from the `mantis` project, although @ieivanov can chime in. 

@ziw-liu and I agreed to go ahead with tagging `main` with `v0.1.0dev0`, and I've started some very early work on `recOrder`  in this [draft PR](https://github.com/mehta-lab/recOrder/pull/331). These tags can be moved/renamed, so this work is still low stakes.

**Comment by ieivanov** [comment]
#97 will not be an issue for the mantis, git tags seem like a good idea to me too

**Comment by ziw-liu** [comment]
Now on [TestPyPI](https://test.pypi.org/project/iohub/). Seems fine. Cannot actually install because dependencies are not available from the test index. But the page looks reasonable enough.

**Comment by ziw-liu** [comment]
Pushed `v0.1.0dev3` to [PyPI](https://pypi.org/project/iohub/0.1.0.dev3/). Thanks for everyone's help!
