### ISSUE TITLE
Method to delete or rename channel in NGFF datasets

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#56]
Branching off of #45:
#31 has a convenience method for appending new channels to a NGFF position node, but there is no easy way to delete or rename an existing channel so that arrays and metadata all get updated properly.

**Comment by ziw-liu** [comment]
Also needed for #10.

**Comment by ziw-liu** [comment]
Now that I've started the implementation, I realized that automatically resizing the array when a channel is deleted (aka 'popping' the channel's corresponding data from the array) is not trivial. 

The easiest way would be to get a selection of the old array (which brings *every* voxel into a NumPy array in RAM) and write that to the old array again, and then resize the array. There are some checks and loops we can put in to handle larger-than-RAM issues or use other libraries like Dask to handle it, but it will always require loading-decompressing-compressing-writing all the data while the task is only to remove some of the data in a regular way.

Meanwhile there're tricks we can play if the chunks do not overlap along the C axis (chunk size TCZYX=`(*,1,*,*,*)`), which is often but not always the case. This is not directly supported by the zarr-python backend though.

Ref: [reordering axis in-place](https://discourse.pangeo.io/t/how-to-efficiently-overwrite-existing-zarr-archive-with-reordered-time-axis-updated-question/2714/11), [Zarr chunking](https://forum.image.sc/t/ome-zarr-chunking-questions/66794/3?page=3)

@AhmetCanSolak @JoOkuma Any ideas?

**Comment by mattersoflight** [comment]
The original motivation for this feature was the need to overwrite a segmentation mask, flatfield image, etc. Can you think of solutions that are easy to discover for users? 
A solution is to provide a convenience method `overwrite_channel` that just calls `__setitem__()` (= operator).

**Comment by ziw-liu** [comment]
> The original motivation for this feature was the need to overwrite a segmentation mask, flatfield image, etc. Can you think of solutions that are easy to discover for users?

For this usage, if the channel is originally created with something like:
https://github.com/czbiohub/iohub/blob/69d518f7092290ce59cacf897b7576c7d6c07740/examples/single_fov_ome_zarr.py#L57-L67

Then I would recommend using the same pattern (`dataset["img"][0, 2] = new_zyx`) to set the values again, so that users do not need to remember additional APIs. But yes a shorthand for that e.g. `overwrite_channel` can be easily implemented.

**Comment by JoOkuma** [comment]
I agree with @ziw-liu comments.
If resizing is really necessary, an option is to limit to e axis where the chunk size is one and reorganize the chunk files and directories without loading the data in memory --- but this could be a bit dangerous, if it crashes, it will lead to a messy structure of zarr chunks.

**Comment by mattersoflight** [comment]
>  But yes a shorthand for that e.g. overwrite_channel can be easily implemented.

👍🏼 That will work well and will be used. A related point is that the channel dimension should be indexable by the name of the channel as well its index. This is needed for virtual staining as we just discussed (https://github.com/mehta-lab/microDL/issues/201).

**Comment by ziw-liu** [comment]
> A related point is that the channel dimension should be indexable by the name of the channel as well its index.

This will likely require a backend change to our image array model. Currently we use `Array` from zarr-python (which I'm personally happy with and will gladly help support tensorstore), and it can only be indexed with`int`, `slice`, boolean masks etc, and the same is true for NumPy and Dask. If we want to index arrays by`str` keys AFAIK the only solution is to use [Xarray](https://docs.xarray.dev/en/stable/). I think AICSImageIO made that choice partly for this reason, but this requires some careful thought and comprehensive discussion about iohub's global data model.

**Comment by ziw-liu** [comment]
> If we want to index arrays by`str` keys AFAIK the only solution is to use [Xarray](https://docs.xarray.dev/en/stable/).

That being said, getting the index for a channel is as easy as `position.channel_names.index("name")`.
