### ISSUE TITLE
Make it easier to write and read `tiled` dataset.

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#59]
Taking this point off of #45.

@mattersoflight suggested:
> * Introduce a `tiles` or `tiled` layout. I picked these words in favor of `multiPos` or `multiFOV`. But, I think either of them is a decent choice.

Along with this usage pattern:

https://github.com/czbiohub/iohub/blob/61237f9a9b7a99eb7a1e74ceaa01c0c93204a518/examples/tiles_zarr.py#L1-L41

**Comment by ziw-liu** [comment]
As far as I can tell, this will require:

1. Designing a custom hierarchy layout and describe it in a specification that devs and users can refer to.
This has been discussed in #22 and the result is achievable with the current API (see [example](https://github.com/czbiohub/iohub/blob/69d518f7092290ce59cacf897b7576c7d6c07740/examples/multi_fov_hcs_ome_zarr.py)).
2. A new class that override the methods (e.g. `create_position()`) of `iohub.ngff.Plate`. This means that the objects returned by the main NGFF entry point for standard and this custom layout will have methods of the same name, but take different arguments and mutate datasets differently.

IMO this is not the safest design/usage pattern to manipulate datasets. I'm also not sure if this will bring significant syntactic benefit considering that it only commits a FOV name argument in the get/set calls.

**Comment by mattersoflight** [comment]
I am thinking of a thin wrapper around `hcs` layout so that when the user uses `tiled` layout, they have to only `row` and `col`, but not `fov`. When the acquisition is tiled, the `fov` parameter doesn't make sense.

**Comment by ziw-liu** [comment]
> When the acquisition is tiled, the `fov` parameter doesn't make sense.

Then how about a `TiledPlate` class that inherits from `ngff.Plate` and adds a couple of *extra* methods. For example `make_tiles(n_rows, n_cols)` or `create_tile(i_row, i_col)`, which hides`fov` by hardcoding its value to `'0'`.

My main concern with overriding existing methods is that it's hard to distinguish between multi-well plates and tiled acquisition when reading user-side code that expect different behavior.

**Comment by ziw-liu** [comment]
@mattersoflight and I just had a chat and realized that tiled acquisitions actually suits well in a chunked array where each acquired frame is a (x_chunksize, y_chunksize) slice of the array. We just need to subclass `ngff.ImageArray` with something like `ngff.TiledImageArray` that has some extra convenience methods to create, read, and write tiles.
