### ISSUE TITLE
Package metadata

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#68]
The current package metadata in [`setup.cfg`](https://github.com/czbiohub/iohub/blob/efbb7f4c9fb992ca332b3d403404efbe22aa0002/setup.cfg#L36) is inherited from waveorder and saw minor revisions. As iohub approaches a PyPI release, we need to agree on some update to the information. (See comments in the code blocks below)

Author and email:

```properties
author = Computational Microscopy Platform, CZ Biohub  # change to CZ Biohub?
author_email = shalin.mehta@czbiohub.org.  # does this need to change?
```

Classiffiers:

```properties
classifiers =
    Development Status :: 4 - Beta. # Alpha?
    Intended Audience :: Science/Research
    License :: OSI Approved :: BSD License  # is 3-clause the original BSD?
    Programming Language :: Python :: 3 :: Only
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Image Processing
    Topic :: Scientific/Engineering :: Visualization  # remove
    Topic :: Scientific/Engineering :: Information Analysis  # remove? this is too generic
    Topic :: Scientific/Engineering :: Bio-Informatics  # remove
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX
    Operating System :: Unix
    Operating System :: MacOS
    # any additional classifiers? 
```

@mattersoflight @AhmetCanSolak @JoOkuma would love to have your input on this.

**Comment by AhmetCanSolak** [comment]
author can be `CZ Biohub and iohub contributors`
author_email could be your email @ziw-liu ? That's my suggestion, Shalin already busy with many other things.
I don't have a strong opinion on development status for now.
License classifier looks fine to me.
We can remove the last three topics as suggested.

**Comment by ziw-liu** [comment]
> author can be `CZ Biohub and iohub contributors`

Do we need to change the license copyright clause accordingly or its ok that they are different?
